
# http://localhost:3000/fr/confirmation?email=contact%40otakedev.com
# docker run --name dev-postgres --network my_dev_network -p 5432:5432 -e POSTGRES_PASSWORD=your_secure_password -d postgres:16-alpine

services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    networks:
      - my_dev_network
    ports:
      - 5432:5432 
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    # build: . # uncomment to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment to build from source
    ports:
      - 3000:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
      - meilisearch
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    env_file:
      - .env
    volumes:
      - ./meili_data:/meili_data
